### ISSUE TITLE
improvement: creating self-transitions

### ISSUE THREAD

**Issue by brunocrosier** [statelyai/studio-issues#101]
Currently, creating a self-transition is quite tricky. You have to pull out from the right, left, or bottom of a node, and connect it to the top bar. 

@mattpocock suggested adding an option to the "selection menu" could be a good way forward

**Comment by mattpocock** [comment]
cc @cirephe here, I agree that creating a transition which targets its own node is not very discoverable.

**Comment by davidkpiano** [comment]
Added to Linear: https://linear.app/statelyai/issue/STA-1594/add-self-transition-to-state-node-context-menu

**Comment by davidkpiano** [comment]
In Canny: https://github.com/statelyai/studio-issues/issues/101

**Comment by mellson** [comment]
This is available later today.
