### ISSUE TITLE
Request: In Simulate mode the highlighting of the current parent state is not very clear for larger models

### ISSUE THREAD

**Issue by reliablecontrols** [statelyai/studio-issues#113]
![image](https://user-images.githubusercontent.com/105379045/174907284-b4c71039-6b69-4996-9ebd-8995ec72b28c.png)

Example. The homepage state highlighting in blue is tough to see in larger model (ie, when the zoom level is 62%).

**Comment by davidkpiano** [comment]
Moved to Canny: https://statelyai.canny.io/editor/p/improve-simulation-mode-design
