### ISSUE TITLE
Spacebar functionality is broken

### ISSUE THREAD

**Issue by umphy** [statelyai/studio-issues#129]
When pressing and holding spacebar:
1. the cursor disappears unless you move it
2. the cursor turns into a hand (like when clicking middle mouse button), but when left-clicking on the mouse, it is still the selection tool rather than panning around the canvas.

https://user-images.githubusercontent.com/1195634/197338881-28f1de5d-887c-44f9-81e2-3bfaeeb0825e.mp4

**Comment by umphy** [comment]
Firefox 106.0.1
MacOS 12.6

Just tested in Chrome and it works fine.

**Comment by davidkpiano** [comment]
Panning with spacebar now works as expected in Firefox:

https://user-images.githubusercontent.com/1093738/204189526-7fadb7dc-cb68-42ab-a8d9-815befcfa249.mp4

The spacebar issue is weird, but it's not unique to the Stately editor; it happens on any other site too:


https://user-images.githubusercontent.com/1093738/204189564-a4d3ba66-f929-4613-9de9-2d1c731e615a.mp4
