### ISSUE TITLE
Bug: VS Code Extension is changing event properties

### ISSUE THREAD

**Issue by acailly** [statelyai/studio-issues#130]
### Description

Very similar with past issue: https://github.com/statelyai/studio-issues/issues/49
The case described in this issue is exactly the same as mine

When I set a transition external, then reopen the editor and open the transition details, the transition is now internal again

### Expected result

The transition is still external as I set it to be

### Actual result

The transition is back to internal

### Which browsers are you seeing the problem on?

Chrome

**Comment by mellson** [comment]
@acailly this should be fixed in the latest releases. Can you check if it works for you?

**Comment by acailly** [comment]
@mellson I confirm everything is working fine now, thank you 🙏

**Comment by mellson** [comment]
> @mellson I confirm everything is working fine now, thank you 🙏

Great to hear. Thanks for confirming!
