### ISSUE TITLE
Bug: Guarded transitions exported with incorrect order

### ISSUE THREAD

**Issue by overtune** [statelyai/studio-issues#131]
Hi!

I have a machine where I have a state which can transition to three other states based on guarded transitions.
But when I export the machine it exports the state like this:
```
"First State": {
      "always": [
        {
          "target": "Second State",
          "cond": "ifCond1"
        },
        {
          "target": "Third State"
        },
        {
          "target": "Fourth State",
          "cond": "ifCond2"
        }
      ]
    },
```

The transition without a guard (the middle one) will always take precedence before the last transition with a guard.
So I guess a target without a guard should always be added last in that list.
(Or is there some way in the editor to edit the order of transitions manually?)

I understand this has to do with in which order the transitions where created, but when working out a state chart it is common to add/remove/edit stuff frequently.

https://stately.ai/registry/editor/9c0f312d-805b-4612-97ba-0061958b91db?machineId=c7ca15d5-a246-4046-bedb-28c209a36a79

**Comment by davidkpiano** [comment]
Thanks for the report; this is tracked here: https://statelyai.canny.io/editor/p/reorder-guarded-transitions-using-the-dot-handle
