### ISSUE TITLE
Bug: Editor layout becomes broken after adding a state to top node with a self transition

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/studio-issues#134]
### Description

From a state machine that has no state and at least one self transition, adding a state breaks the editor's layout for the nodes.

![image](https://user-images.githubusercontent.com/12085950/198703088-16bbc603-d460-4b99-b320-94780c17bf75.png)

### Expected result

![image](https://user-images.githubusercontent.com/12085950/198702749-002f5f65-6890-46c7-a2d2-039f9f20cef0.png)

### Actual result

![image](https://user-images.githubusercontent.com/12085950/198702976-e6673325-3f60-4fb0-83ac-e7b9023093db.png)

### Which browsers are you seeing the problem on?

Chrome

### Additional details

Refreshing the page or the extension tab fixes the issue.

**Comment by davidkpiano** [comment]
This no longer occurs 🎉
