### ISSUE TITLE
data keys getting removed

### ISSUE THREAD

**Issue by erikras** [statelyai/studio-issues#139]
The VSCode extension version of the editor is, since at least yesterday, actively deleting my `data` keys from my `invoke`s.

This is _no bueno_!!

<img width="762" alt="Screenshot 2022-11-11 at 11 02 42 AM" src="https://user-images.githubusercontent.com/4396759/201317219-a4b7310e-a82f-40f2-b4c9-c222cc899b1c.png">

**Comment by Andarist** [comment]
Got fixed by https://github.com/statelyai/xstate-tools/pull/229 . The actual release is still pending though. Thanks for helping out with QAing and beta testing this, Erik!
