### ISSUE TITLE
Editor doesn't support XState built-in actions

### ISSUE THREAD

**Issue by tivac** [statelyai/studio-issues#14]
We use a lot of `send()`/`raise()` actions in our statecharts, and currently the editor doesn't support those. It should though, because they're an important part of building a statechart and being able to handle communication across multiple trees of states.

**Comment by davidkpiano** [comment]
Added to Linear: https://linear.app/statelyai/issue/STA-1347/support-for-action-parameters

**Comment by davidkpiano** [comment]
In Canny: https://statelyai.canny.io/editor/p/built-in-actions
