### ISSUE TITLE
Unreachable parent state with reachable children

### ISSUE THREAD

**Issue by mubaraqwahab** [statelyai/studio-issues#141]
The Editor labels a parent state as "unreachable" if there's no transition from a reachable state to it, even if there are transitions from a reachable state to its children.

Compare this:

![image](https://user-images.githubusercontent.com/48601635/201745584-536aa239-7411-4635-abc6-b86bdd344a1a.png)
 
to this, where there's a transition to the parent state itself from a reachable state:

![image](https://user-images.githubusercontent.com/48601635/201746188-0e601118-18ea-437d-b051-cf9d5bb2a418.png)

Is this the intended behaviour?

[Link to the machine](https://stately.ai/registry/editor/2663c7e1-df77-460e-a394-8c767cb9c960)

**Comment by davidkpiano** [comment]
This has been fixed 

<img width="838" alt="CleanShot 2023-07-27 at 13 43 11@2x" src="https://github.com/statelyai/studio-issues/assets/1093738/213e5933-8989-4a8c-bed0-840b396613f6">
