### ISSUE TITLE
Bug: Rendering issue while dragging a state with multiple child nodes

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/studio-issues#143]
### Description

When dragging a state that contains more than one child node, the rendering becomes broken as soon as you reach the left side of the editor.

It's also affecting child nodes and not just the top node.

### Expected result

Continue to render nodes at correct position while dragging.

### Actual result

Rendering breaks while dragging.

### Which browsers are you seeing the problem on?

Chrome

### Additional details

Chrome Version 107.0.5304.107 (Official Build) (64-bit)
Windows 10

https://user-images.githubusercontent.com/12085950/203799162-65f49d22-a24e-461d-97ad-a09c9bb62285.mp4

https://user-images.githubusercontent.com/12085950/203797932-07a853d4-4d65-40ea-a926-2c9fb01e14fd.mp4

**Comment by Valkendorm** [comment]
After a hard refresh, and clearing site data, it still happens, but on the right side now. I tried it on a separate computer (with latest Edge on Windows 11) and get the dragging issue, but in any direction.

The only place where it's not happening for me is from the VSC extension.

**Comment by Valkendorm** [comment]
Unfortunately, it's still happening with the latest studio. Reproduced on 3 different PCs and browsers (Edge, Chrome, Firefox), all Windows. Tried with hardware acceleration disabled as well.

**Comment by Andarist** [comment]
@Valkendorm would you be able to record an anonymous session using https://app.replay.io/ ? This would allow us to see exactly what is going on in our logic

**Comment by davidkpiano** [comment]
Tried to reproduce this in the latest version but was unable to:

https://user-images.githubusercontent.com/1093738/208560140-77bba152-2fae-4df3-9811-c213b34128f9.mp4

@Valkendorm Can you try one last time? Lots of updates were made in the last 3 weeks.

**Comment by Valkendorm** [comment]
I was experimenting on the issue this morning and discovered that if I drag the machine far enough to the left or right side, it will stop having the issue. If I drag it back to the previous area, the issue will come back.

https://user-images.githubusercontent.com/12085950/208695551-a1740ba0-1d25-46f3-8a0e-dbba3eb1c96f.mp4

Since I was getting the issue with the landing page machine, maybe it has something to do with being close to center position on the grid?

**Comment by davidkpiano** [comment]
I was testing on Chrome where I was not able to reproduce the issue, but I now see that I can reproduce it in Firefox.

**Comment by davidkpiano** [comment]
I'm no longer able to reproduce this in Firefox 😌 


https://user-images.githubusercontent.com/1093738/217421323-31e2edca-a4ea-4ade-8e25-68db21289165.mp4



Substantial improvements were made to layout in the editor; there's a good chance that those improvements fixed this issue.
