### ISSUE TITLE
Bug: Studio becomes unresponsive after dragging an event's source back to original state

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/studio-issues#145]
### Description

From any state, dragging an event's source to the same state will make the Studio become unresponsive.

### Expected result

Studio should remain responsive.

### Actual result

Studio becomes unresponsive (infinite loop).

### Which browsers are you seeing the problem on?

Chrome

### Additional details

Reproducible on Chrome and Firefox (haven't tried others).

https://user-images.githubusercontent.com/12085950/204903697-d9ea4c99-b49c-47a7-a461-689766f4c74c.mp4

**Comment by davidkpiano** [comment]
Thanks for the report. Fix for this being released soon.

**Comment by Andarist** [comment]
The fix has been merged already - we plan to release it shortly.
