### ISSUE TITLE
Bug: Focusing on another node won't register the description's field change

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/studio-issues#146]
### Description

Typing inside a node's **description** field and directly selecting another node won't register the change.

Doing the same action for a **guard** will register the change.

### Expected result

Register change made to the description.

### Actual result

Change is lost.

### Which browsers are you seeing the problem on?

Chrome

### Additional details

https://user-images.githubusercontent.com/12085950/205364862-2a05f524-3f07-4958-9dc4-6aaee3416409.mp4

**Comment by Andarist** [comment]
Thanks for the report! I will take a look at this.

**Comment by Andarist** [comment]
I've prepared an internal PR with a fix for this. The underlying culprit was this beautiful issue 😅 : https://github.com/facebook/react/issues/12363
