### ISSUE TITLE
bug: History state doesn't toggle between shallow and deep history after state creation

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/studio-issues#15]
1. Add a State (and keep it selected)
2. Set its type to History from the Edit panel
3. Click on the Shallow/Deep toggle (nothing happens)

Strangely, double-clicking on the toggle will work. Clicking elsewhere (even key or description field) will also make it work after.

**Comment by davidkpiano** [comment]
This has since been fixed 

https://github.com/statelyai/studio-issues/assets/1093738/2915be0e-fc83-48dc-b702-7e72cee59d9a
