### ISSUE TITLE
Bug: Import code adds quotes to named actions

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/studio-issues#151]
### Description

When adding a machine with the **Import code** option, the generated machine will have quotes added to named actions from event, entry and exit.

Using the example code below:

```js
createMachine({
  id: "test",
  initial: "one",
  states: {
    one: {
      entry: ["doEntryStuff"],
      exit: ["doExitStuff"],
      on: {
        STEP: {
          actions: ["doActionOne", "doActionTwo"],
          target: "two"
        }
      }
    },
    two: {
      invoke: {
        src: "doInvokeThing",
        onDone: {
          actions: ["doInvokeDoneActionOne", "doInvokeDoneActionTwo"],
          target: "one"
        }
      },
      on: {
        STEP: {
          target: "one",
          cond: "isCondFulfilled"
        }
      }
    }
  }
})
```

Turns into this once imported (export tab):

```js
createMachine({
  id: "test",
  initial: "one",
  states: {
    one: {
      entry: '"doEntryStuff"',
      exit: '"doExitStuff"',
      on: {
        STEP: {
          target: "two",
          actions: ['"doActionOne"', '"doActionTwo"'],
        },
      },
    },
    two: {
      invoke: {
        src: "doInvokeThing",
        onDone: [
          {
            target: "one",
            actions: ['"doInvokeDoneActionOne"', '"doInvokeDoneActionTwo"'],
          },
        ],
      },
      on: {
        STEP: {
          target: "one",
          cond: "isCondFulfilled",
        },
      },
    },
  },
  context: {},
  predictableActionArguments: true,
  preserveActionOrder: true,
});
```

### Expected result

Imported machine shouldn't add quotes to named actions.

### Actual result

Quotes are added to named actions (Invokes and guards are unaffected by the issue).

![image](https://user-images.githubusercontent.com/12085950/213289164-dae686ce-d305-441c-b065-04fcf352942b.png)

### Which browsers are you seeing the problem on?

Chrome

### Additional details

Reproducible using machines that use single or double quotes.

Note: Tried using backticks and the result is quite different (some parts are lost in the process).

**Comment by davidkpiano** [comment]
Thanks for the report. We have a fix for this in review 👍

**Comment by farskid** [comment]
This is fixed in latest Studio.
