### ISSUE TITLE
Browser hangs trying to load team project

### ISSUE THREAD

**Issue by aceslick911** [statelyai/studio-issues#152]
Hello - can't get into my team as the browser keeps crashing

![image](https://user-images.githubusercontent.com/1932043/213964785-cd005118-3696-42fb-b1c0-299864289234.png)

I setup chrome debugger to break on uncaught exceptions and was able to get this error to be reported. Must be happening on a loop or something

![image](https://user-images.githubusercontent.com/1932043/213964846-b3974321-145c-4de1-a279-f6837a63ce95.png)
![image](https://user-images.githubusercontent.com/1932043/213964860-3e3ac5ec-8a86-46bc-a64e-c8e5027b230b.png)
![image](https://user-images.githubusercontent.com/1932043/213964875-172c5111-3f67-4c5f-8d1f-803650178a09.png)

Link - WARNING will crash your tab!

https://stately.ai/registry/editor/ef4327bb-5ad0-476e-b852-4f1b9306bfa9?machineId=afa8ab3c-4484-4fce-b738-e315ee030614

**Comment by davidkpiano** [comment]
Uh oh - sorry about this, and thank you for reporting! We'll investigate ASAP.

**Comment by mellson** [comment]
Hi @aceslick911 👋🏻 your project should work again. Sorry for the trouble.

**Comment by aceslick911** [comment]
Thankyou! @davidkpiano @mellson  works 👌 great job and incredible turnaround time 🤯
