### ISSUE TITLE
Bug: Unable to create new machines despite being a pro customer

### ISSUE THREAD

**Issue by aceslick911** [statelyai/studio-issues#153]
### Description

Reproduction steps:
1. Be logged in via github
2. Go to team (of 1) project
3. Project opens successfully
4. Click create new machine button (+)

![image](https://user-images.githubusercontent.com/1932043/214164991-3a6a8dac-a427-4130-bdc0-15278215e022.png)
url at the time: https://stately.ai/registry/editor/ef4327bb-5ad0-476e-b852-4f1b9306bfa9?machineId=88aef9bc-2db5-424b-b5a6-8e33a94f6dbd

5. Error message shown
6. Click on team project again on left side
7. Error message: `This team is read-only and some functionality may be limited.`

![image](https://user-images.githubusercontent.com/1932043/214165087-7b359b6d-c4b7-4b3a-833f-1da2fc766eaa.png)

It's saying I need a pro subscription but the user dropdown seems to think I already do 🤔 

Didn't get any emails from stripe regarding failed payments or anything..

### Expected result

Be able to create new machines and edit old ones

### Actual result

Possibly stuck in a read-only state

### Which browsers are you seeing the problem on?

Chrome

### Additional details

This team project previously had 2 contributors but I changed it back to 1 as I only am paying for 1 user right now (myself)

**Comment by aceslick911** [comment]
Checked my billing events

![image](https://user-images.githubusercontent.com/1932043/214168910-fee5f67f-0482-44f9-b102-e52b6b64ac84.png)

Also I already got a refund for the extra payments I believe

**Comment by kevinmaes** [comment]
Hi @aceslick911 Thanks for reporting this. I'll investigate the issue and get back to you soon. Thanks for your patience.

**Comment by aceslick911** [comment]
No problem @kevinmaes - I mentioned this is not high priority for me at the moment so triage as needed 👍

**Comment by kevinmaes** [comment]
Hi @aceslick911 Please give it a try now and let me know if the problem seems to be resolved. Thanks!

**Comment by aceslick911** [comment]
Thanks :) looks like it's working again!

**Comment by kevinmaes** [comment]
> Thanks :) looks like it's working again!

Awesome! Thanks for the update!
