### ISSUE TITLE
Bug: Copy+Pasting states and events to another compound state causes new states+events to be pasted with incorrect layout (inverted y axis)

### ISSUE THREAD

**Issue by aceslick911** [statelyai/studio-issues#155]
### Description

1. Copy a pre-layed out statechart eg:
![image](https://user-images.githubusercontent.com/1932043/218878818-f423836d-5d68-472d-a84b-3e98510134ef.png)

2. Paste it into another state

### Expected result

Expect the relative positioning of states and events to be maintained such as in the original copied compound state:
![image](https://user-images.githubusercontent.com/1932043/218879235-701dbd48-2526-45e8-b855-51091a0a761e.png)

### Actual result

![image](https://user-images.githubusercontent.com/1932043/218878983-809616a4-a8e7-4321-aa50-414e86b25cd3.png)

### Which browsers are you seeing the problem on?

Chrome

### Additional details

eg: https://stately.ai/registry/editor/06d6ab71-0d23-40f1-b9ce-b31ff9667159?machineId=08712cdf-55c5-4082-aeb2-9cae7bc53e24

**Comment by davidkpiano** [comment]
Thanks for the report. We need to rework copy-paste in general, and future improvements will definitely come with layout improvements as well.

**Comment by davidkpiano** [comment]
This has since been fixed.
