### ISSUE TITLE
Crashes when viewing code

### ISSUE THREAD

**Issue by marssantoso** [statelyai/studio-issues#156]
Link to troubled file: https://stately.ai/registry/editor/64adfec2-7c31-4b42-970f-0b8de92d0a52?machineId=3b69f2d4-44dd-4b11-92fd-acb5ca265140

Steps to reproduce:

- Open the link above
- Click the `code` icon on the right

I think it has something to do with some of the context being objects, as well as assigning to said context directly from actions with inline function. 

Here's the same machine but with a working file, after removing some context and assignments: https://stately.ai/registry/editor/64adfec2-7c31-4b42-970f-0b8de92d0a52?machineId=8323ed5d-8c67-48f4-a6e2-9701a5cc46ed

---
Studio version: 0.38.0

**Comment by davidkpiano** [comment]
Thanks for the report. We are prioritizing this and working on it.

**Comment by marssantoso** [comment]
That was impressively quick...

Thanks, guys. Great work 🙌
