### ISSUE TITLE
Export provides code for older version

### ISSUE THREAD

**Issue by solidsnack** [statelyai/studio-issues#158]
Exporting machine `3e4004af-62bb-4490-9be1-3a7985c481b6` doesn't export the current machine definition (the one displayed) but rather an older one.

---
Studio version: 0.39.0

**Comment by farskid** [comment]
@solidsnack Thank you for reporting this issue. I took a quick look at https://stately.ai/registry/editor/c49ce613-5f47-4575-aef6-dd78ec6103e4?machineId=3e4004af-62bb-4490-9be1-3a7985c481b6&mode=Design and can't seem to figure out where the issue is exactly.

I see the machine as 
<img width="1349" alt="CleanShot 2023-04-01 at 20 27 09@2x" src="https://user-images.githubusercontent.com/8332043/229305708-93fbf5ce-ba7a-49d7-8e90-e37d037b3951.png">
and the TypeScript export is as follows:
```ts
createMachine({
  id: "field<Data, Underlying>",
  states: {
    input: {
      initial: "empty",
      states: {
        empty: {
          on: {
            "input(content: Underlying)": {
              target: "input(content: Underlying)",
            },
          },
        },
        "input(content: Underlying)": {
          on: {
            "input(content: Underlying)": {
              target: "input(content: Underlying)",
              internal: false,
            },
            "clear()": {
              target: "empty",
            },
          },
        },
      },
    },
    validity: {
      initial: "validating",
      states: {
        "invalid(message: text)": {
          on: {
            "input(content: Underlying)": {
              target: "validating",
            },
            "clear()": {
              target: "validating",
            },
          },
        },
        "valid(value: Data)": {
          on: {
            "input(content: Underlying)": {
              target: "validating",
            },
            "clear()": {
              target: "validating",
            },
          },
        },
        validating: {
          on: {
            "validate()": [
              {
                target: "valid(value: Data)",
                cond: "content.into()",
              },
              {
                target: "invalid(message: text)",
              },
            ],
            "input(content: Underlying)": {},
            "clear()": {},
          },
        },
      },
    },
  },
  type: "parallel",
  schema: {
    events: {} as
      | { type: "validate()" }
      | { type: "input(content: Underlying)" }
      | { type: "clear()" },
  },
  predictableActionArguments: true,
  preserveActionOrder: true,
});
```

**Comment by solidsnack** [comment]
It definitely is working now; but earlier, the `clear()` transitions in the `validity` machine, among others, were not showing up. Unfortunately, I did not record the JSON that I saw at the time. A apologize for my error.

**Comment by farskid** [comment]
No problem. Glad it's working now. Let us know if you encounter it again.
> It definitely is working now; but earlier, the `clear()` transitions in the `validity` machine, among others, were not showing up. Unfortunately, I did not record the JSON that I saw at the time. A apologize for my error.
