### ISSUE TITLE
feature request: Export machines as JS objects

### ISSUE THREAD

**Issue by horacioh** [statelyai/studio-issues#2]
as a user, I want to export machines as JS objects so I can just paste it on my programs without doing an extra transformation on a spooky website with millions of ads

**Comment by mattpocock** [comment]
You can already export a machine as JSON, is this not what you meant? You're imagining exporting it like this:

```ts
const machine = createMachine({
  id: 'My Machine'
})
```

**Comment by mattpocock** [comment]
I think you'll like the VSCode integration we're building, this manages this formatting out of the box.

**Comment by horacioh** [comment]
you can mark this as "silly nice to have", but yes is about exporting not in JSON (with `"` wrapping keys) but as JS.

**Comment by davidkpiano** [comment]
Moved to Canny: https://statelyai.canny.io/devtools/p/export-to-jsts
