### ISSUE TITLE
Add SVG export of statechart

### ISSUE THREAD

**Issue by tivac** [statelyai/studio-issues#20]
Would be nice to have a static version I can share w/ the team that they can browse to better understand the overall flow, but I don't necessarily want them to use the editor and accidentally change something (or maybe they're not in the editor beta!).

Also it's hard to share it with a screenshot once you clear a certain size, even on a big 4k monitor I can't make it big enough to capture all the detail. An exported SVG would be able to be perfectly scaled/scrolled for browsing.

**Comment by davidkpiano** [comment]
Tracked internally: https://linear.app/statelyai/issue/STA-675/export-to-svg

**Comment by davidkpiano** [comment]
In Canny: https://statelyai.canny.io/editor/p/export-to-svg
