### ISSUE TITLE
bug: Remove ability to add states on final state nodes

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/studio-issues#22]
And should probably also highlight that the children states are now invalid when switching a parent state to final.

![image](https://user-images.githubusercontent.com/12085950/150983328-55e33f9a-9fcb-4c29-9df2-0639a77df82d.png)

**Comment by mattpocock** [comment]
Labelling as an enhancement - there is more to think about here, such as whether changing a node's type to final should delete all its child nodes.

**Comment by davidkpiano** [comment]
Tracked internally: https://linear.app/statelyai/issue/STA-1222/non-compound-states-should-not-have-ability-to-add-child-states

**Comment by mattpocock** [comment]
@davidkpiano We should also show error messages on all recursive children of final state nodes, saying 'this shouldn't be here'

**Comment by davidkpiano** [comment]
We now show this warning:

<img width="328" alt="CleanShot 2023-11-29 at 17 10 16@2x" src="https://github.com/statelyai/studio-issues/assets/1093738/709a56db-1472-4269-8b3a-79ac59728927">
