### ISSUE TITLE
[VSC extension] Events/invokes with guards can become hidden or render partially

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/studio-issues#27]
Seems related to event's placement and only affects the extension so far.

![image](https://user-images.githubusercontent.com/12085950/151173670-3b24e017-f8be-4613-a74f-fe19008dc4f1.png)

![image](https://user-images.githubusercontent.com/12085950/151174114-274d5943-421d-4e00-a119-f84113f88a76.png)

**Comment by mellson** [comment]
This should be fixed. Please let us know if you experience this again.
