### ISSUE TITLE
suggestion: Active states in the simulator should be outlined and not filled

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/studio-issues#3]
It's a little hard (and distracting) to make the difference between a state and an event in the simulator. In the Viz, active states only have an outline and I think it works better.

I just also noticed that possible transitions are also highlighted.

### Simulator

![image](https://user-images.githubusercontent.com/12085950/150791093-d83f534c-430b-4670-92df-809141f0f089.png)

### Viz

![image](https://user-images.githubusercontent.com/12085950/150790992-14c523b4-db29-4992-8451-49a384524ab9.png)

**Comment by mattpocock** [comment]
Agree, we are not happy with the designs currently. We have some work in the pipeline to improve it a lot.

**Comment by davidkpiano** [comment]
In Canny: https://statelyai.canny.io/editor/p/improve-simulation-mode-design
