### ISSUE TITLE
[VSC Extension] The @xstate-layout comment is added right after the variable name on fresh files

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/studio-issues#35]
Version: 1.5.10

![image](https://user-images.githubusercontent.com/12085950/151805306-ace295f3-ea94-4375-b913-7318e9c2b8fb.png)

If you move that comment over the variable and reload it in the editor, it will stay at its proper place.

**Comment by davidkpiano** [comment]
In Canny: https://statelyai.canny.io/devtools/p/hide-layout-comment
