### ISSUE TITLE
Having a History state as the initial state prevents the editor from simulating

### ISSUE THREAD

**Issue by edgerunner** [statelyai/studio-issues#38]
### Steps to reproduce

1. Add a history state
2. Make it the initial state
3. Click the simulate tab

Then nothing happens. Possibly, because there isn't a way (at least an obvious one) to define a default state for when there's no history. 

### Additional problems

- It isn't possible to define a transition from a history state, but it is possible to convert a normal state to history without losing the transitions. The above situation doesn't change even if the history has an `always` transition on it pointing to another state.
- It is possible to convert a compound state to `history`, without losing the inner structure. No idea what that does.

### How it should behave

- It should be possible to define a default state to follow a history state
- There should be some sort of error message if the simulation can't start for any reason

**Comment by davidkpiano** [comment]
Added to Linear: https://linear.app/statelyai/issue/STA-1124/having-a-history-state-as-the-initial-state-prevents-the-editor-from

**Comment by davidkpiano** [comment]
There is now validation for this: 

![CleanShot 2022-10-23 at 12 21 31@2x](https://user-images.githubusercontent.com/1093738/197389223-9dabb86d-42d1-4a20-887a-7ea27e3bf24a.png)

**Comment by edgerunner** [comment]
Harel's history states can be the initial state with an *always* transition serving as the default for when there's no history. Any ideas to implement that behavior?

<img width="146" alt="image" src="https://user-images.githubusercontent.com/15765/197396379-fd3b31f2-4d33-4735-8522-c0838a6d5abc.png">
