### ISSUE TITLE
Changing the name of the system > machine in the editor lost all of my transitions

### ISSUE THREAD

**Issue by jmakeig** [statelyai/studio-issues#43]
After I changed the name of the machine from the editor settings all of [my transitions disappeared](https://stately.ai/registry/editor/a9514ba5-4851-4cad-9d36-413e9e6dfc79). I thought it was a rendering issue, but the overview says it really does have 0 transitions.  

Here’s the [equivalent exported from the editor into the visualizer](https://stately.ai/viz/096e972f-bf6c-4b20-88d3-dac3a0087ee6). (Copy-pasta to the rescue!)

**Comment by jmakeig** [comment]
Aside: I wonder if there could be tighter integration between the editor and the visualizer. The editor is definitely easier and faster to edit machine definitions. However, I lean heavily on the visualizer to test side effects.

**Comment by mattpocock** [comment]
Damn, that's very annoying. Sorry about that! Thanks for the bug report.

**Comment by mattpocock** [comment]
> Aside: I wonder if there could be tighter integration between the editor and the visualizer. The editor is definitely easier and faster to edit machine definitions. However, I lean heavily on the visualizer to test side effects.

Could you raise this as a separate issue? Sounds interesting and would be good to discuss.

**Comment by davidkpiano** [comment]
This should no longer occur ✅

**Comment by if-fi** [comment]
Forgot to mention the above thing happened in the online editor, **not** the VS Code extension
