### ISSUE TITLE
Machine menu is not always obvious

### ISSUE THREAD

**Issue by simonflk** [statelyai/studio-issues#5]
My first time using the editor, I created a "Contact us" machine to model a contact form.

...confusion ensued when I looked to find where to share/export the machine from, as I thought the "Contact us" menu was part of the app, and not related to my machine 😄 

![image](https://user-images.githubusercontent.com/4867329/150840128-4fb07b0f-3b00-4862-b982-3464cf5710de.png)

**Comment by davidkpiano** [comment]
Added to Linear: https://linear.app/statelyai/issue/STA-1283/make-machine-dropdown-title-clearer

**Comment by davidkpiano** [comment]
The UI has been changed and this is no longer applicable.
