### ISSUE TITLE
Simulating with an 'on delay' event will block full simulation

### ISSUE THREAD

**Issue by Glutnix** [statelyai/studio-issues#51]
Currently a simulation of a delay event does not invoke automatically after the delay, nor can it be invoked manually, blocking simulation of the downstream states of the machine.

Suggestion: activate the delay events like other events, or simulate the delay with a progress bar. Add a setting to switch between either of these behaviours.

**Comment by davidkpiano** [comment]
Delayed transitions are supported in the current version of the editor.
