### ISSUE TITLE
Forking other user's machine seems to erase events

### ISSUE THREAD

**Issue by karkowg** [statelyai/studio-issues#53]

**Comment by davidkpiano** [comment]
As in the transitions disappear?

**Comment by karkowg** [comment]
Yes, only the states remain.

**Comment by davidkpiano** [comment]
I can no longer reproduce this - events are preserved when forking a machine.

Please re-open if you have a specific machine that you can reproduce this issue with.

**Comment by Gongreg** [comment]
Copying an example of reproduction here: https://stately.ai/registry/editor/ff936e9a-3d2f-4845-83d0-bf5c8f342721

**Comment by Gongreg** [comment]
Can confirm that the fix is live now. @davidkpiano - you can close the issue again :)
