### ISSUE TITLE
Rename selected when hitting Enter key 

### ISSUE THREAD

**Issue by MagedEWilliam** [statelyai/studio-issues#54]
i want to be able to rename the key of the selected node by hitting the enter key.
the current method to rename relays on the mouse.

the current method:
![the current method](https://user-images.githubusercontent.com/8369718/158942663-8073cf88-564a-47a8-b6c7-0e079f4e7e74.gif)

**Comment by mattpocock** [comment]
@MagedEWilliam Could you provide a more detailed description? What are the reproduction steps?

**Comment by MagedEWilliam** [comment]
@mattpocock description updated.

**Comment by davidkpiano** [comment]
So when a node or edge label is selected, you want to press the enter key to rename it? That makes sense 👍

**Comment by mattpocock** [comment]
@MagedEWilliam You can double-click the node or edge to rename inline - does this feel equally convenient?

**Comment by MagedEWilliam** [comment]
Umm Yes it's convenient,
But it would be nice to have.
Coming from figma i instinctively expected it.
Also i planned on giving more feedback that are shortcut related, but i understand if it's not a priority.

**Comment by davidkpiano** [comment]
Pressing enter to rename an edge label is also useful for a keyboard-only flow, once we have a better story around selecting nodes with the keyboard.
