### ISSUE TITLE
Rendering Issue during event/state boundary collisions

### ISSUE THREAD

**Issue by K3TH3R** [statelyai/studio-issues#55]
This was the original event I discovered that triggers a display issue with the Actions panel when adding a guard.

https://user-images.githubusercontent.com/11901111/156503801-fe9a67db-5f38-4683-a809-330ac77a7a9c.mov

I've also discovered since that it appears to possibly be due to an issue with collision detection which you can also see in this video where I'm not adding a guard, but simply moving an event around:

https://user-images.githubusercontent.com/11901111/156504018-b918ac71-d04c-4c01-bc4d-455480457cb8.mov

In the case of the first video, I think the addition of the guard forced the box down, creating the boundary collision with the state below it which caused the rendering/event disappearance issue.

**Comment by davidkpiano** [comment]
Doing some cleanup; this should no longer be an issue.
