### ISSUE TITLE
Indicate when Undo and Redo are exhausted

### ISSUE THREAD

**Issue by laurakalbag** [statelyai/studio-issues#56]
When you have exhausted all undos or redos, it would be useful for the UI to indicate that there’s no point continuing to press those buttons.

We should disable the button (if it isn’t already) and provide a visual indicator that the button is disabled.

**Comment by davidkpiano** [comment]
This is fixed ✅ 


https://user-images.githubusercontent.com/1093738/197389550-f769aa6e-eddb-4ccf-bb30-89ea76184b30.mp4
