### ISSUE TITLE
[Feature requests] collapsible states?(hide/show parts of machine)

### ISSUE THREAD

**Issue by mikementor** [statelyai/studio-issues#6]
Once the machine becomes bigger, there will be hard to navigate with all the details on the surface.
I want to be able to hide/show implementation details from bigger abstraction for ease of reasoning

**Comment by tom-sherman** [comment]
Should the canvas and treeview nodes be independently collapsible, or should their state be mirrored?

**Comment by davidkpiano** [comment]
> Should the canvas and treeview nodes be independently collapsible, or should their state be mirrored?

I think these should be separate, but that's just my instinct.

------

When collapsing parent nodes, what should happen to the area the parent once took? If you create a node in that area, and then _expand_ the parent, the node will overlap the parent, which is not desirable.

**Comment by davidkpiano** [comment]
In Canny: https://statelyai.canny.io/editor/p/nested-folding
