### ISSUE TITLE
create a way to keep newly created event within its parent state

### ISSUE THREAD

**Issue by trafnar** [statelyai/studio-issues#66]
often when creating events within a state, there isn't enough room to place it comfortably. If I drag it too, it is placed outside the parent. If I keep it inside, it is very cramped and requires me to fix it separately.

One way to fix this would be to have a hotkey you hold down to either keep it inside, or default it to staying inside its parent and have a hotkey to let it go outside.

![Screen Recording (Code)](https://user-images.githubusercontent.com/6732/159211391-0029e2af-536a-491a-ae82-659b9651fb4e.gif)

**Comment by mattpocock** [comment]
cc @davidkpiano - I like this idea.

**Comment by davidkpiano** [comment]
Another idea that supports non-keyboard devices in the future (such as an iPad): if you're dragging to create a new state node and _inside_ a parent for some amount of time, "lock" the new state node to be inside the parent:

<img width="796" alt="CleanShot 2022-03-30 at 08 26 28@2x" src="https://user-images.githubusercontent.com/1093738/160834029-05ca3e96-2cb4-4001-880f-8e7a32d5e836.png">

**Comment by davidkpiano** [comment]
Added to Linear: https://linear.app/statelyai/issue/STA-1601/keep-new-event-in-compound-state-mode

**Comment by davidkpiano** [comment]
Moved to Canny: https://statelyai.canny.io/editor/p/contain-newly-created-transitions-to-state
