### ISSUE TITLE
lines are drawn under the notes section of states

### ISSUE THREAD

**Issue by trafnar** [statelyai/studio-issues#69]
If you add a note to a state, it seems to be at the wrong z-index, lines are drawn under it, but above everything else.

<img width="391" alt="image" src="https://user-images.githubusercontent.com/6732/159379686-0e10175a-4478-4f9e-8fba-acf077fe9680.png">

**Comment by davidkpiano** [comment]
Added to Linear: https://linear.app/statelyai/issue/STA-1288/edges-should-not-overlap-parts-of-node

**Comment by davidkpiano** [comment]
This no longer occurs ✅
