### ISSUE TITLE
[Feature request] Referencing other machines in machines

### ISSUE THREAD

**Issue by mikementor** [statelyai/studio-issues#7]
I want to make some building blocks (like authorization, or List ) and construct the bigger machine from them. Don't know how to do this now
(Probably slightly related(not quite,but a bit) to https://github.com/statelyai/editor-feedback/issues/6)

**Comment by davidkpiano** [comment]
Added to Linear: https://linear.app/statelyai/issue/STA-1282/listing-machines-to-invoke

**Comment by MichelChanthavong** [comment]
@mikementor 
I struggle with the same issue. It would really be a great improvement !

**Comment by davidkpiano** [comment]
In Canny: https://statelyai.canny.io/editor/p/link-machines-in-same-system
