### ISSUE TITLE
[BUG] Parellel State could not trigger `onDone` event

### ISSUE THREAD

**Issue by FeliciousX** [statelyai/studio-issues#79]
# Description
After all the states inside a parallel state reaches `final`, it does not trigger the `onDone` transition.

[reproduction link](https://stately.ai/registry/editor/9fe831f7-f0aa-4887-be38-f93ca2b76e3d)

## Initial State
![image](https://user-images.githubusercontent.com/701633/162090659-4b4e96f5-0bc9-41ba-86a3-700ddacdbe1c.png)

## Fetch A completes
![image](https://user-images.githubusercontent.com/701633/162090923-04e721bd-2937-4c1e-b8d2-77f3ef331a36.png)

## Fetch B completes
(BUG HERE! should move from `loading -- onDone --> idle`)
![image](https://user-images.githubusercontent.com/701633/162090973-8e1bad5e-790c-4943-a812-9bb4faa985f2.png)

**Comment by davidkpiano** [comment]
Added to Linear: https://linear.app/statelyai/issue/STA-1316/parallel-state-could-not-trigger-ondone-event

**Comment by mattpocock** [comment]
PR'd this to closed-source repo

**Comment by davidkpiano** [comment]
This is now fixed
