### ISSUE TITLE
My systems editor view versus stately.ai viz

### ISSUE THREAD

**Issue by chrisribe** [statelyai/studio-issues#80]
It would be nice to be able to switch from editor mode to https://stately.ai/viz mode where you can see the code, state, events and actors. 
![image](https://user-images.githubusercontent.com/1999791/162839755-89009164-4a1a-4a9b-87f1-f9387993fccc.png)

I just feels odd you sometimes see the registry editor sometimes the other viewer.

**Comment by mattpocock** [comment]
@chrisribe Could you clarify what you mean? Do you mean inside VSCode or in general on the web?

**Comment by chrisribe** [comment]
I mean in general when navigating on the website it get's confusing as you sometimes are directed to:
https://stately.ai/viz or https://stately.ai/registry/editor

![image](https://user-images.githubusercontent.com/1999791/164724155-5cd14ec6-a40b-41b7-a648-e1ba89579cfa.png)

Both have a similar feel (editor vs visualizer) and you cannot go from the editor to the visualiser. So all you are left with is the simulate button in the editor. 

If I where to want to use the visualiser I need to export the json, open the page, paste it in the code section and run. Having a button in the editor could be a nice shortcut, I think.

**Comment by mattpocock** [comment]
Gotcha, you basically want to be able to import to the editor from the visualizer, and vice versa

**Comment by chrisribe** [comment]
Yes that sums it up nicely.

Also I feel that the https://stately.ai/registry/discover section should only show the visualizer. Having a mixed list is confusing imho.

**Comment by nspaeth** [comment]
The editor does not include things like `Actor`, or the ability to view/modify the json currently and that would be nice. Can the editor and visualizer just be merged into one interface and then just make systems you don't own non-editable?

**Comment by davidkpiano** [comment]
> The editor does not include things like `Actor`, or the ability to view/modify the json currently and that would be nice. Can the editor and visualizer just be merged into one interface and then just make systems you don't own non-editable?

Yes, this is the eventual plan.

**Comment by davidkpiano** [comment]
In Canny: https://statelyai.canny.io/editor/p/improve-simulation-mode
