### ISSUE TITLE
Setting an "initial" state for Auto-Layout left-alignment?

### ISSUE THREAD

**Issue by ericclemmons** [statelyai/studio-issues#82]
Often the `IDLE` state is the starting state, so it makes sense to appear at the left.  (`FINAL` states are expected to appear at the right)

When having sequential, circular states that go back to `IDLE`, the order doesn't match that 1,2,3,4 steps you'd expect:

> <img width="562" alt="Screen Shot 2022-04-12 at 12 34 02 PM" src="https://user-images.githubusercontent.com/15182/163020804-b0c67e29-b538-4458-89d5-86b59876da68.png">

**Comment by davidkpiano** [comment]
Added to Linear: https://linear.app/statelyai/issue/STA-1598/improve-autolayout-algorithm

**Comment by davidkpiano** [comment]
In Canny: https://statelyai.canny.io/editor/p/autolayout-improvements
