### ISSUE TITLE
Can the xstate-layout hash live outside of the code

### ISSUE THREAD

**Issue by saadshahd** [statelyai/studio-issues#84]
Hey Team,

When the new stately editor is being used locally inside vscode;

- Can the xstate-layout hash live out of the code may be inside:
   - .xstate-layout file inside the same folder as the machine?
   - or even inside the .vscode folder?

**Comment by mattpocock** [comment]
Added an internal RFC about this.

**Comment by davidkpiano** [comment]
In Canny: https://statelyai.canny.io/devtools/p/hide-layout-comment
