### ISSUE TITLE
Hitting the DEL key while dragging a new event from the top state will leave the "new event" dragbox visible

### ISSUE THREAD

**Issue by Valkendorm** [statelyai/studio-issues#96]
Select the top state, drag one of the dots to get the "new event" dragbox, then hit the DEL key. The state will be unselected, but the dragbox will also remain visible until the next drag is initiated.

![image](https://user-images.githubusercontent.com/12085950/169110366-dec68e6f-10d1-4008-a11a-2f9bda0cdce8.png)

This is only happening on the top state. On any other state, the state is deleted and the dragbox is properly taken care of.

**Comment by davidkpiano** [comment]
That's the part of our codebase that doesn't have a state machine! 🤦 

Thanks for reporting this. Added to Linear https://linear.app/statelyai/issue/STA-1464/hitting-the-del-key-while-dragging-a-new-event-from-the-top-state-will

**Comment by davidkpiano** [comment]
This has been fixed.
