### ISSUE TITLE
Tried to backup machine using fork feature and it ended up losing all my changes from the session

### ISSUE THREAD

**Issue by aceslick911** [statelyai/studio-issues#97]
Hello,
was making changes on a machine and then used the fork feature into the same system which saved an old version of my machine. Lost all my work as well 🤷 

![image](https://user-images.githubusercontent.com/1932043/169173433-3a1d21a5-7bf2-42b0-90c7-ce5530d2d71b.png)

**Comment by davidkpiano** [comment]
Very sorry that this happened – by chance, are you able to reproduce this issue?
